### ISSUE TITLE
Proizvoljan broj vozila

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-006-plugger#4]
Pokušajte da modifikujete program da umesto da imate fiksirana 4 vozila, da imate niz vozila gde ih može biti proizvoljno mnogo (na primer, niz pokazivača na strukturu koja pamti traku na putu, poziciju i tip vozila).

**Comment by pecurka** [comment]
@ivan-cukic-matf Trebalo bi da je sada okej, možete testirati tako što promenite vrednost numberOfVehicles 👍
